/**
 * WannaGo Client API
 * This is a sample Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BookingPost { 
    /**
     * id cuả user đặt booking
     */
    userId?: number;
    /**
     * Tênc của khách hàng, phải trùng tên CMND
     */
    customerName?: string;
    /**
     * Số đt liên hệ xác minh khi đặt phòng
     */
    phone?: string;
    /**
     * email gửi cho người booking, có thể khác email của tài khoản
     */
    email?: string;
    /**
     * id của stay được booking
     */
    stayId?: number;
    /**
     * ngày check in
     */
    checkIn?: string;
    /**
     * ngày check out
     */
    checkOut?: string;
    /**
     * Số lượng khách đăng booking
     */
    guestCount?: number;
    /**
     * giá tiền tính theo check-in và check-out
     */
    totalPrice?: number;
    /**
     * code giao dịch
     */
    paymentCode?: string;
    /**
     * - 1 : 'Chờ thanh toán | Payment pending' - 2 : 'Đã thanh toán | Payment success' 
     */
    statusCode?: number;
    /**
     * Tên trạng thái của booking - 'Đã thanh toán' - 'Chờ thanh toán' 
     */
    status?: string;
}