/**
 * WannaGo Client API
 * This is a sample Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StayAddress } from './stayAddress';
import { StayUtility } from './stayUtility';

export interface StayDetail { 
    /**
     * Id của Host
     */
    hostId?: number;
    /**
     * stay_type from m_code
     */
    stayTypeName?: string;
    /**
     * stay_id
     */
    stayId?: number;
    /**
     * stay_name
     */
    stayName?: string;
    /**
     * rating_point
     */
    rate?: number;
    /**
     * rating count
     */
    ratingCount?: number;
    /**
     * guest_count
     */
    guestCount?: number;
    /**
     * bed_count
     */
    bedCount?: number;
    /**
     * bath_count
     */
    bathCount?: number;
    /**
     * price
     */
    price?: number;
    /**
     * discounted price
     */
    discount?: number;
    stayAddress?: StayAddress;
    stayUtility?: StayUtility;
    imgUrls?: Array<string>;
}